{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "6d4e68de-82ea-4802-bccc-9d6ca47ae232",
   "metadata": {},
   "source": [
    "Q1. What is an Exception in python? Write the difference between Exceptions and syntax errors Ans.\n",
    "\n",
    "In Python, an exception is a runtime error that occurs during the execution of a program. When an exceptional situation arises, Python raises an exception, indicating that something unexpected or erroneous has happened. Exceptions allow the program to handle errors gracefully and provide a way to propagate error information up the call stack.\n",
    "\n",
    "Differences between Exceptions and Syntax Errors:\n",
    "\n",
    "Occurrence: Exception: Exceptions occur during the runtime of a program when an error condition is encountered while executing code. Syntax Error: Syntax errors, also known as parsing errors, occur when the Python interpreter encounters code that does not follow the proper syntax rules of the language. These errors happen before the code is executed. Handling:\n",
    "\n",
    "Exception: Exceptions can be caught and handled using try-except blocks, allowing the program to gracefully recover from the error and continue its execution. Syntax Error: Syntax errors cannot be caught or handled within the program. They need to be fixed by the developer before the code can be successfully executed. Examples:\n",
    "\n",
    "Exception: Examples of exceptions include ZeroDivisionError, TypeError, IndexError, ValueError, etc. For instance, trying to divide a number by zero or accessing an index that doesn't exist in a list would raise exceptions. Syntax Error: Examples of syntax errors include forgetting a colon at the end of an if statement, using an invalid character in a variable name, or mismatched parentheses and syntax errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "36e2884a-b711-4520-aab7-0d65e437f29b",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. What happens when an exception is not handled? Explain with an example.\n",
    "\n",
    "When an exception is not handled, it propagates up the call stack until it reaches the top-level scope of the program.\n",
    "If the exception is still not handled at this point, the program will terminate, and an error message, including the exception's type and details, will be displayed. \n",
    "This abrupt termination is known as an \"unhandled exception\" or \"uncaught exception.\"\n",
    "\n",
    "Eg-\n",
    "l = [12,4,5,6,7]\n",
    "l[10]\n",
    "\n",
    "It will show this -\n",
    "---------------------------------------------------------------------------\n",
    "IndexError                                Traceback (most recent call last)\n",
    "Cell In[1], line 2\n",
    "      1 l = [12,4,5,6,7]\n",
    "----> 2 l[10]\n",
    "\n",
    "IndexError: list index out of range"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0f4dc26-f469-43f2-95fe-aa5fb3c7dbbb",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3.Which Python statements are used to manage and handle exceptions? Explain with an example.\n",
    "Ans.\n",
    "\n",
    "In Python, try, except, else, and finally statements are used to manage and handle exceptions. \n",
    "These statements allow you to gracefully handle errors and implement error recovery mechanisms in your code.\n",
    "\n",
    "Eg-\n",
    "try:\n",
    "    f=open(\"test.txt\",'w')\n",
    "    f.write(\"Hello\")\n",
    "except Exception as e:\n",
    "    print(\"There is some issue\" + e)\n",
    "else:\n",
    "    print(\"This block will execute once try will execute itself without an exception\")\n",
    "finally:\n",
    "    print(\"This block will always execute\")\n",
    "    f.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "03a3a487-0ed0-49a5-b2c3-afc7674651ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Explain with an example.\n",
    "a. try and else\n",
    "b. finally\n",
    "c. raise\n",
    "\n",
    "Ans.\n",
    "a.\n",
    "In Python, the try and else blocks are used for handling exceptions in code.\n",
    "An exception is an error that occurs during the execution of a program, disrupting the normal flow of the program. \n",
    "Using these blocks allows you to handle potential errors gracefully and take appropriate actions.\n",
    "\n",
    "try:\n",
    "    f=open(\"test.txt\",'w')\n",
    "    f.write(\"Hello\")\n",
    "except Exception as e:\n",
    "    print(\"There is some issue\" + e)\n",
    "else:\n",
    "    f.close()\n",
    "    \n",
    "b.\n",
    "The finally block is used in conjunction with try and except blocks and provides a way to ensure that some code is executed no matter what, \n",
    "whether an exception occurred or not.\n",
    "\n",
    "try:\n",
    "    f=open(\"test.txt\",'w')\n",
    "    f.write(\"Hello\")\n",
    "except Exception as e:\n",
    "    print(\"There is some issue\" + e)\n",
    "else:\n",
    "    print(\"This block will execute once try will execute itself without an exception\")\n",
    "finally:\n",
    "    print(\"This block will always execute\")\n",
    "    f.close()\n",
    "    \n",
    "c.\n",
    "The raise keyword in Python is used to manually raise exceptions. \n",
    "It allows you to trigger specific exceptions when certain conditions are met.\n",
    "\n",
    "class validateage(Exception):\n",
    "    def __int__(self,msg):\n",
    "        self.msg = msg\n",
    "\n",
    "def validate_age(age):\n",
    "        if age<0:\n",
    "            raise validateage(\"Age shouldn't be less that 0\")\n",
    "        elif age>200:\n",
    "            raise validateage(\"Age too high\")\n",
    "        else:\n",
    "            print(\"Age is valid\")\n",
    "                   \n",
    "try:\n",
    "    age = input(\"Enter your age\")\n",
    "    validate_age(age)\n",
    "except validate_age as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6b0dda17-ed6a-4a8e-abd3-664fbffa25b5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f81abd8e-1527-4661-b708-31bbe3de30d4",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "50742306-8fd2-4a7b-8de9-6a9454b7e425",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
